version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - mvn clean package

reports:
  CiReports:
    files:
      - "junit.xml"
    discard-paths: yes    
